---
title: "MRC examples"
format: html
toc: true
---

# Set up
```{r}
#| label: setup
#| message: false
#| warning: false

library("tidyverse")
library("ds4ling")
library("untidydata")
library("broom")
library("emmeans")
```


# Tidy data
```{r}
#| label: explore-data

ld <- language_diversity %>%
  mutate_if(is.character, as.factor) %>%
    pivot_wider(
    names_from = Measurement,
    values_from = Value
  ) %>%
  mutate(
    lang_log = log(Langs),
    area_log = log(Area),
    pop_log = log(Population)
  )

summary(ld)
dim(ld)
str(ld)
glimpse(ld)
# View(ld) delete it when you have to render

```


# Analysis
```{r}
#| label: fit-model

mean(ld$lang_log)

mod_0 <- lm(lang_log ~ 1, data = ld)
mod_1 <- lm(lang_log ~ 1 + pop_log, data = ld)
mod_2 <- lm(lang_log ~ 1 + pop_log + area_log, data = ld)
mod_3 <- lm(lang_log ~ 1 + pop_log + area_log + pop_log:area_log, data = ld)
summary(mod_0)
summary(mod_1)
summary(mod_2)
summary(mod_3)
```


# Tables and plots

Hello, please appreciate @tbl-model1, even though it is not better than @tbl-model3

```{r}
#| label: tbl-model1
#| tbl-cap: "Hello"

tidy(mod_1) %>%
  knitr::kable(format = "pandoc")

```


```{r}
#| label: tbl-model3
#| tbl-cap: "Hello"

tidy(mod_3) %>%
  knitr::kable(format = "pandoc")

```



```{r}

emmeans(
  object = mod_1,
  specs =  ~ pop_log,
  at = list(pop_log = seq(0, 20, by = 1))
)
```

```{r}

emmeans(
  object = mod_3,
  specs =  ~ pop_log * area_log,
  at = list(pop_log = c(0, 10, 20),
            area_log = c(0, 10, 20))
)
```

